sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PTPbJXPHMxSqR0gtWU85vxmVsVPL2zruNLyupwgoaSUV5qUdIBwUbIcIvXYxyRwGndAQv7c9LPtQ49NFhon9FPK9yNnc3yOeA0r4IF3qOSr6uPvYIeMBAyJUwZ4LNjLXlCRR7DYZa/npFUCvngYQzHi+oos9PO84OGod/x4J4mdyhwC+INGoBhAIbjtPp8uvs6A9FuDHAaySmR05PxfG4o27SgHR+VcQGtZXTbBFROrergPq603WBsLrrla1bNYDyMRIsWPy+OzocTgkzPdfHhwgtlPM8yUbAJ81N2TAy1aMoSaGITZiUmVNWSbiphuQ/LOsmKLLPPNjLSmRAyi8fhNkKhrQ60N/i3D97u2482nAHtorj6LGT7zF3S//2/Wp5AKCvLmUhDjVvRjFdqZYkRR27POxHNe6fEqSHh+/jzObdAtVSCxepol1xP+5qncBfJ4FJl2fCa2Mi8PPBO4tvTfMwfy92DuTKAFZUckEvUnr1G/moatZcOTeHshzWp0+V7C/3WjziC5wDZO+bBP+UAq+4zdGN/0FjGrhjseenebKdTp/7SFP0SSatGJzpxB6hUV4+UNOeKNC1F7/cNCStxUTolQQbon2S7b/jzjfldUu4ILbc16NW1PLp6HcaJwwvdgkI+lcpaWf2iv8tTXfOUQZtS0BbeIQVO5neIqcRmk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Histoire-des-voyages-de-Scarmentado_4718
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy